# Generated by Django 4.1 on 2022-08-23 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taluk_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Taluk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.taluk_choices')),
            ],
        ),
    ]
