# Generated by Django 4.1 on 2022-08-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0002_taluk_choices_taluk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taluk_choices',
            options={'verbose_name_plural': 'Taluk choices'},
        ),
        migrations.CreateModel(
            name='Sakha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sakha_no', models.CharField(max_length=50)),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.taluk_choices')),
            ],
        ),
    ]
