# Generated by Django 4.1 on 2022-08-24 04:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0003_alter_taluk_choices_options_sakha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SubCaste_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Matrimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=25)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Un Married', 'Un Married'), ('Divorced', 'Divorced'), ('Widow', 'Widow')], max_length=25)),
                ('photo', models.ImageField(upload_to='pictures')),
                ('education_qualification', models.CharField(max_length=250)),
                ('occupation', models.CharField(max_length=250)),
                ('district', models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], max_length=250)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.gender_choices')),
                ('subcaste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.subcaste_choices')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.taluk_choices')),
            ],
        ),
    ]
