# Generated by Django 4.1 on 2022-08-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0004_gender_choices_subcaste_choices_matrimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender_choices',
            options={'verbose_name_plural': 'Gender'},
        ),
        migrations.AlterModelOptions(
            name='subcaste_choices',
            options={'verbose_name_plural': 'Sub Caste'},
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='brother',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='father_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='hobbies',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='languages',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='mother_name',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='sister',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='total_family_members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='work_place',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
