# Generated by Django 4.1 on 2022-08-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0006_matrimonial_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonial',
            name='note',
        ),
        migrations.AddField(
            model_name='matrimonial',
            name='status',
            field=models.CharField(default='Pending', max_length=25),
        ),
    ]
