# Generated by Django 4.1 on 2022-08-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0007_remove_matrimonial_note_matrimonial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonial',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=25),
        ),
    ]
