# Generated by Django 4.1 on 2022-08-24 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0008_alter_matrimonial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonial',
            name='languages',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='taluk',
            field=models.CharField(max_length=50),
        ),
    ]
