# Generated by Django 4.1 on 2022-08-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0009_alter_matrimonial_languages_alter_matrimonial_taluk'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrimonial',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
