# Generated by Django 4.1 on 2022-08-30 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0012_alter_matrimonial_gaurdian_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matrimonial',
            name='gaurdian_mobile',
        ),
    ]
