# Generated by Django 3.2.9 on 2022-08-31 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0013_remove_matrimonial_gaurdian_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrimonial',
            name='father_occupation',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='gaurdian_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='languages',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='mother_occupation',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='star',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kvs_app.star'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='subcaste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kvs_app.subcaste_choices'),
        ),
        migrations.AlterField(
            model_name='matrimonial',
            name='total_family_members',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
