# Generated by Django 4.1 on 2022-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0014_auto_20220831_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='sakha',
            name='sakaha_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
