# Generated by Django 4.1 on 2022-09-21 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0015_sakha_sakaha_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Id_details_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Id choices',
            },
        ),
        migrations.CreateModel(
            name='Insurence_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Insurence category',
            },
        ),
        migrations.CreateModel(
            name='Payment_details_choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Payment Details choices',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile_no', models.CharField(max_length=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('id_no', models.CharField(max_length=25)),
                ('sakha_no', models.CharField(max_length=25)),
                ('taluk', models.CharField(max_length=25)),
                ('proposed_by_name', models.CharField(blank=True, max_length=25, null=True)),
                ('proposed_by_contact_no', models.CharField(blank=True, max_length=25, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.insurence_category')),
                ('id_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.id_details_choices')),
                ('payment_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.payment_details_choices')),
            ],
        ),
    ]
