# Generated by Django 3.2.9 on 2022-09-22 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0016_id_details_choices_insurence_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='id_details_choices',
            options={'verbose_name_plural': 'Id card choices'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'Services'},
        ),
        migrations.CreateModel(
            name='Join_Kvs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('place', models.CharField(max_length=25)),
                ('taluk', models.CharField(max_length=25)),
                ('sakha_no', models.CharField(default='New Member', max_length=25)),
                ('id_proof_no', models.CharField(max_length=25)),
                ('id_proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kvs_app.id_details_choices')),
                ('payment_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kvs_app.payment_details_choices')),
            ],
        ),
    ]
