# Generated by Django 3.2.9 on 2022-09-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0017_auto_20220922_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='join_kvs',
            options={'verbose_name_plural': 'Join Kvs'},
        ),
        migrations.AddField(
            model_name='join_kvs',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=25),
        ),
    ]
