# Generated by Django 4.1 on 2023-01-24 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0020_statecommitie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_kvs',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='join_kvs',
            name='district',
            field=models.CharField(blank=True, choices=[('Trivandrum', 'Trivandrum'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='join_kvs',
            name='membership_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='join_kvs',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kvs_app.gender_choices'),
        ),
        migrations.AddField(
            model_name='join_kvs',
            name='union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kvs_app.taluk_choices'),
        ),
    ]
