# Generated by Django 3.2.9 on 2023-01-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0023_remove_join_kvs_taluk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender_choices',
            options={'verbose_name_plural': 'Add Gender'},
        ),
        migrations.AlterModelOptions(
            name='id_details_choices',
            options={'verbose_name_plural': 'Add Id card choices'},
        ),
        migrations.AlterModelOptions(
            name='insurence_category',
            options={'verbose_name_plural': 'Add Insurence category'},
        ),
        migrations.AlterModelOptions(
            name='payment_details_choices',
            options={'verbose_name_plural': 'Add Payment Details choices'},
        ),
        migrations.AlterModelOptions(
            name='sex_choices',
            options={'verbose_name_plural': 'Add Sex'},
        ),
        migrations.AlterModelOptions(
            name='star',
            options={'verbose_name_plural': 'Add Star'},
        ),
        migrations.AlterModelOptions(
            name='subcaste_choices',
            options={'verbose_name_plural': 'Add Subcaste'},
        ),
        migrations.AlterModelOptions(
            name='taluk_choices',
            options={'verbose_name_plural': 'Add Union'},
        ),
    ]
