# Generated by Django 3.2.9 on 2023-01-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0026_join_kvs_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='join_kvs',
            name='staff_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
