# Generated by Django 3.2.9 on 2023-01-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0027_join_kvs_staff_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join_kvs',
            name='staff_name',
        ),
    ]
