# Generated by Django 4.1 on 2023-02-06 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0031_alter_statecommitie_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='statecommitie',
            name='district',
            field=models.CharField(choices=[('Trivandrum', 'Trivandrum'), ('Kollam', 'Kollam'), ('Pathanamthitta', 'Pathanamthitta'), ('Alappuzha', 'Alappuzha'), ('Kottayam', 'Kottayam'), ('Idukki', 'Idukki'), ('Ernakulam', 'Ernakulam'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Malappuram', 'Malappuram'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod')], default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statecommitie',
            name='place',
            field=models.CharField(max_length=250),
        ),
    ]
