# Generated by Django 4.1 on 2023-02-06 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0032_statecommitie_district_alter_statecommitie_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statecommitie',
            name='district',
        ),
    ]
