# Generated by Django 4.1 on 2023-08-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0037_databank_alter_matrimonial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databank',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
