# Generated by Django 4.1 on 2023-08-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvs_app', '0038_alter_databank_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='databank',
            name='status',
            field=models.CharField(choices=[('Hide', 'Hide'), ('Unhide', 'Unhide')], default='Unhide', max_length=25),
        ),
    ]
